- name: package update
  apt:
    upgrade: dist
- name: install common package
  apt:
    name:
      - less
      - vim
      - jq
    state: present

- name: set hosts
  copy:
    src: ./files/hosts
    dest: /etc/hosts

- name: set sysctl.conf
  copy:
    src: ./files/sysctl.conf
    dest: /etc/sysctl.conf

- name: apply sysctl.conf
  shell: /sbin/sysctl -p

- name: file descripter
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: nofile
    value: 655360
  with_items:
    - domain: root
      limit_type: soft
    - domain: root
      limit_type: hard
    - domain: "*"
      limit_type: soft
    - domain: "*"
      limit_type: hard

- name: install datadog
  when: ddapikey is defined
  shell: DD_API_KEY={{ddapikey}} bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/datadog-agent/master/cmd/agent/install_script.sh)"

